// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/agent_api.dart';
import 'api/agents_api.dart';
import 'api/config_api.dart';
import 'api/cron_api.dart';
import 'api/cron_notification_api.dart';
import 'api/knowledge_api.dart';
import 'api/proxy_api.dart';
import 'api/routes_api.dart';
import 'api/sessions_api.dart';
import 'api/simple.dart';
import 'api/skills_api.dart';
import 'api/workspace_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AgentEvent> dco_decode_StreamSink_agent_event_Sse(dynamic raw);

  @protected
  RustStreamSink<CronNotification> dco_decode_StreamSink_cron_notification_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentConfigDto dco_decode_agent_config_dto(dynamic raw);

  @protected
  AgentEvent dco_decode_agent_event(dynamic raw);

  @protected
  AppConfig dco_decode_app_config(dynamic raw);

  @protected
  AutonomyConfig dco_decode_autonomy_config(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppConfig dco_decode_box_autoadd_app_config(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DelegateAgentDto dco_decode_box_autoadd_delegate_agent_dto(dynamic raw);

  @protected
  EmbeddingConfigDto dco_decode_box_autoadd_embedding_config_dto(dynamic raw);

  @protected
  EmbeddingRouteDto dco_decode_box_autoadd_embedding_route_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  KnowledgeEntry dco_decode_box_autoadd_knowledge_entry(dynamic raw);

  @protected
  ModelRouteDto dco_decode_box_autoadd_model_route_dto(dynamic raw);

  @protected
  ProxyConfigDto dco_decode_box_autoadd_proxy_config_dto(dynamic raw);

  @protected
  SessionDetail dco_decode_box_autoadd_session_detail(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ChannelSummary dco_decode_channel_summary(dynamic raw);

  @protected
  ChatSessionInfo dco_decode_chat_session_info(dynamic raw);

  @protected
  CostConfigDto dco_decode_cost_config_dto(dynamic raw);

  @protected
  CronConfigDto dco_decode_cron_config_dto(dynamic raw);

  @protected
  CronJobDto dco_decode_cron_job_dto(dynamic raw);

  @protected
  CronNotification dco_decode_cron_notification(dynamic raw);

  @protected
  CronRunDto dco_decode_cron_run_dto(dynamic raw);

  @protected
  DelegateAgentDto dco_decode_delegate_agent_dto(dynamic raw);

  @protected
  EmbeddingConfigDto dco_decode_embedding_config_dto(dynamic raw);

  @protected
  EmbeddingRouteDto dco_decode_embedding_route_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeatureToggles dco_decode_feature_toggles(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KnowledgeEntry dco_decode_knowledge_entry(dynamic raw);

  @protected
  KnowledgeStats dco_decode_knowledge_stats(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentEvent> dco_decode_list_agent_event(dynamic raw);

  @protected
  List<ChannelSummary> dco_decode_list_channel_summary(dynamic raw);

  @protected
  List<CronJobDto> dco_decode_list_cron_job_dto(dynamic raw);

  @protected
  List<CronRunDto> dco_decode_list_cron_run_dto(dynamic raw);

  @protected
  List<DelegateAgentDto> dco_decode_list_delegate_agent_dto(dynamic raw);

  @protected
  List<EmbeddingRouteDto> dco_decode_list_embedding_route_dto(dynamic raw);

  @protected
  List<KnowledgeEntry> dco_decode_list_knowledge_entry(dynamic raw);

  @protected
  List<ModelRouteDto> dco_decode_list_model_route_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderInfo> dco_decode_list_provider_info(dynamic raw);

  @protected
  List<ProxyServiceInfo> dco_decode_list_proxy_service_info(dynamic raw);

  @protected
  List<SessionFileEntry> dco_decode_list_session_file_entry(dynamic raw);

  @protected
  List<SessionMessage> dco_decode_list_session_message(dynamic raw);

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw);

  @protected
  List<SkillDto> dco_decode_list_skill_dto(dynamic raw);

  @protected
  List<SkillToolDto> dco_decode_list_skill_tool_dto(dynamic raw);

  @protected
  List<ToolInfo> dco_decode_list_tool_info(dynamic raw);

  @protected
  List<ToolSpecDto> dco_decode_list_tool_spec_dto(dynamic raw);

  @protected
  MemoryConfigDto dco_decode_memory_config_dto(dynamic raw);

  @protected
  ModelRouteDto dco_decode_model_route_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DelegateAgentDto? dco_decode_opt_box_autoadd_delegate_agent_dto(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  KnowledgeEntry? dco_decode_opt_box_autoadd_knowledge_entry(dynamic raw);

  @protected
  SessionDetail? dco_decode_opt_box_autoadd_session_detail(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ProviderInfo dco_decode_provider_info(dynamic raw);

  @protected
  ProviderType dco_decode_provider_type(dynamic raw);

  @protected
  ProxyConfigDto dco_decode_proxy_config_dto(dynamic raw);

  @protected
  ProxyScopeDto dco_decode_proxy_scope_dto(dynamic raw);

  @protected
  ProxyServiceInfo dco_decode_proxy_service_info(dynamic raw);

  @protected
  RuntimeStatus dco_decode_runtime_status(dynamic raw);

  @protected
  SessionDetail dco_decode_session_detail(dynamic raw);

  @protected
  SessionFileEntry dco_decode_session_file_entry(dynamic raw);

  @protected
  SessionMessage dco_decode_session_message(dynamic raw);

  @protected
  SessionStats dco_decode_session_stats(dynamic raw);

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw);

  @protected
  SkillDto dco_decode_skill_dto(dynamic raw);

  @protected
  SkillToolDto dco_decode_skill_tool_dto(dynamic raw);

  @protected
  SkillsConfigDto dco_decode_skills_config_dto(dynamic raw);

  @protected
  ToolInfo dco_decode_tool_info(dynamic raw);

  @protected
  ToolSpecDto dco_decode_tool_spec_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceConfig dco_decode_workspace_config(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AgentEvent> sse_decode_StreamSink_agent_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<CronNotification> sse_decode_StreamSink_cron_notification_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentConfigDto sse_decode_agent_config_dto(SseDeserializer deserializer);

  @protected
  AgentEvent sse_decode_agent_event(SseDeserializer deserializer);

  @protected
  AppConfig sse_decode_app_config(SseDeserializer deserializer);

  @protected
  AutonomyConfig sse_decode_autonomy_config(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppConfig sse_decode_box_autoadd_app_config(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DelegateAgentDto sse_decode_box_autoadd_delegate_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmbeddingConfigDto sse_decode_box_autoadd_embedding_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmbeddingRouteDto sse_decode_box_autoadd_embedding_route_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  KnowledgeEntry sse_decode_box_autoadd_knowledge_entry(
    SseDeserializer deserializer,
  );

  @protected
  ModelRouteDto sse_decode_box_autoadd_model_route_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProxyConfigDto sse_decode_box_autoadd_proxy_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDetail sse_decode_box_autoadd_session_detail(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ChannelSummary sse_decode_channel_summary(SseDeserializer deserializer);

  @protected
  ChatSessionInfo sse_decode_chat_session_info(SseDeserializer deserializer);

  @protected
  CostConfigDto sse_decode_cost_config_dto(SseDeserializer deserializer);

  @protected
  CronConfigDto sse_decode_cron_config_dto(SseDeserializer deserializer);

  @protected
  CronJobDto sse_decode_cron_job_dto(SseDeserializer deserializer);

  @protected
  CronNotification sse_decode_cron_notification(SseDeserializer deserializer);

  @protected
  CronRunDto sse_decode_cron_run_dto(SseDeserializer deserializer);

  @protected
  DelegateAgentDto sse_decode_delegate_agent_dto(SseDeserializer deserializer);

  @protected
  EmbeddingConfigDto sse_decode_embedding_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmbeddingRouteDto sse_decode_embedding_route_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeatureToggles sse_decode_feature_toggles(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KnowledgeEntry sse_decode_knowledge_entry(SseDeserializer deserializer);

  @protected
  KnowledgeStats sse_decode_knowledge_stats(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentEvent> sse_decode_list_agent_event(SseDeserializer deserializer);

  @protected
  List<ChannelSummary> sse_decode_list_channel_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<CronJobDto> sse_decode_list_cron_job_dto(SseDeserializer deserializer);

  @protected
  List<CronRunDto> sse_decode_list_cron_run_dto(SseDeserializer deserializer);

  @protected
  List<DelegateAgentDto> sse_decode_list_delegate_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EmbeddingRouteDto> sse_decode_list_embedding_route_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<KnowledgeEntry> sse_decode_list_knowledge_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelRouteDto> sse_decode_list_model_route_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderInfo> sse_decode_list_provider_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyServiceInfo> sse_decode_list_proxy_service_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionFileEntry> sse_decode_list_session_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionMessage> sse_decode_list_session_message(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<SkillDto> sse_decode_list_skill_dto(SseDeserializer deserializer);

  @protected
  List<SkillToolDto> sse_decode_list_skill_tool_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ToolInfo> sse_decode_list_tool_info(SseDeserializer deserializer);

  @protected
  List<ToolSpecDto> sse_decode_list_tool_spec_dto(SseDeserializer deserializer);

  @protected
  MemoryConfigDto sse_decode_memory_config_dto(SseDeserializer deserializer);

  @protected
  ModelRouteDto sse_decode_model_route_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DelegateAgentDto? sse_decode_opt_box_autoadd_delegate_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  KnowledgeEntry? sse_decode_opt_box_autoadd_knowledge_entry(
    SseDeserializer deserializer,
  );

  @protected
  SessionDetail? sse_decode_opt_box_autoadd_session_detail(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ProviderInfo sse_decode_provider_info(SseDeserializer deserializer);

  @protected
  ProviderType sse_decode_provider_type(SseDeserializer deserializer);

  @protected
  ProxyConfigDto sse_decode_proxy_config_dto(SseDeserializer deserializer);

  @protected
  ProxyScopeDto sse_decode_proxy_scope_dto(SseDeserializer deserializer);

  @protected
  ProxyServiceInfo sse_decode_proxy_service_info(SseDeserializer deserializer);

  @protected
  RuntimeStatus sse_decode_runtime_status(SseDeserializer deserializer);

  @protected
  SessionDetail sse_decode_session_detail(SseDeserializer deserializer);

  @protected
  SessionFileEntry sse_decode_session_file_entry(SseDeserializer deserializer);

  @protected
  SessionMessage sse_decode_session_message(SseDeserializer deserializer);

  @protected
  SessionStats sse_decode_session_stats(SseDeserializer deserializer);

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer);

  @protected
  SkillDto sse_decode_skill_dto(SseDeserializer deserializer);

  @protected
  SkillToolDto sse_decode_skill_tool_dto(SseDeserializer deserializer);

  @protected
  SkillsConfigDto sse_decode_skills_config_dto(SseDeserializer deserializer);

  @protected
  ToolInfo sse_decode_tool_info(SseDeserializer deserializer);

  @protected
  ToolSpecDto sse_decode_tool_spec_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceConfig sse_decode_workspace_config(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_agent_event_Sse(
    RustStreamSink<AgentEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_cron_notification_Sse(
    RustStreamSink<CronNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_config_dto(
    AgentConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_event(AgentEvent self, SseSerializer serializer);

  @protected
  void sse_encode_app_config(AppConfig self, SseSerializer serializer);

  @protected
  void sse_encode_autonomy_config(
    AutonomyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_config(
    AppConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delegate_agent_dto(
    DelegateAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_embedding_config_dto(
    EmbeddingConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_embedding_route_dto(
    EmbeddingRouteDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_knowledge_entry(
    KnowledgeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_model_route_dto(
    ModelRouteDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proxy_config_dto(
    ProxyConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_detail(
    SessionDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_channel_summary(
    ChannelSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_session_info(
    ChatSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cost_config_dto(CostConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_cron_config_dto(CronConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_cron_job_dto(CronJobDto self, SseSerializer serializer);

  @protected
  void sse_encode_cron_notification(
    CronNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cron_run_dto(CronRunDto self, SseSerializer serializer);

  @protected
  void sse_encode_delegate_agent_dto(
    DelegateAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embedding_config_dto(
    EmbeddingConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embedding_route_dto(
    EmbeddingRouteDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_feature_toggles(
    FeatureToggles self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_knowledge_entry(
    KnowledgeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_knowledge_stats(
    KnowledgeStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_event(
    List<AgentEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_channel_summary(
    List<ChannelSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cron_job_dto(
    List<CronJobDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cron_run_dto(
    List<CronRunDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_delegate_agent_dto(
    List<DelegateAgentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_embedding_route_dto(
    List<EmbeddingRouteDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_knowledge_entry(
    List<KnowledgeEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_route_dto(
    List<ModelRouteDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_info(
    List<ProviderInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_service_info(
    List<ProxyServiceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_file_entry(
    List<SessionFileEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_message(
    List<SessionMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_skill_dto(List<SkillDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_skill_tool_dto(
    List<SkillToolDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tool_info(List<ToolInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tool_spec_dto(
    List<ToolSpecDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_config_dto(
    MemoryConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_route_dto(ModelRouteDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_delegate_agent_dto(
    DelegateAgentDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_knowledge_entry(
    KnowledgeEntry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_detail(
    SessionDetail? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_provider_info(ProviderInfo self, SseSerializer serializer);

  @protected
  void sse_encode_provider_type(ProviderType self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_config_dto(
    ProxyConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_scope_dto(ProxyScopeDto self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_service_info(
    ProxyServiceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_status(RuntimeStatus self, SseSerializer serializer);

  @protected
  void sse_encode_session_detail(SessionDetail self, SseSerializer serializer);

  @protected
  void sse_encode_session_file_entry(
    SessionFileEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_message(
    SessionMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_stats(SessionStats self, SseSerializer serializer);

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_skill_dto(SkillDto self, SseSerializer serializer);

  @protected
  void sse_encode_skill_tool_dto(SkillToolDto self, SseSerializer serializer);

  @protected
  void sse_encode_skills_config_dto(
    SkillsConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tool_info(ToolInfo self, SseSerializer serializer);

  @protected
  void sse_encode_tool_spec_dto(ToolSpecDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_config(
    WorkspaceConfig self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
