// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent_api.dart';
import 'api/config_api.dart';
import 'api/simple.dart';
import 'api/workspace_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 441113648;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_deskclaw',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AppConfig> crateApiConfigApiAppConfigDefault();

  Future<void> crateApiAgentApiClearSession();

  ChatSessionInfo crateApiAgentApiCreateSession();

  Future<AgentConfigDto> crateApiWorkspaceApiGetAgentConfig();

  Future<AutonomyConfig> crateApiWorkspaceApiGetAutonomyConfig();

  Future<CostConfigDto> crateApiWorkspaceApiGetCostConfig();

  Future<AppConfig> crateApiAgentApiGetCurrentConfig();

  Future<MemoryConfigDto> crateApiWorkspaceApiGetMemoryConfig();

  Future<RuntimeStatus> crateApiAgentApiGetRuntimeStatus();

  Future<WorkspaceConfig> crateApiWorkspaceApiGetWorkspaceConfig();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiAgentApiInitRuntime();

  Future<List<ChannelSummary>> crateApiWorkspaceApiListChannels();

  List<ProviderInfo> crateApiConfigApiListProviders();

  List<ToolSpecDto> crateApiAgentApiListTools();

  Future<List<ToolInfo>> crateApiWorkspaceApiListToolsWithStatus();

  Future<AppConfig> crateApiConfigApiLoadConfig();

  Future<bool> crateApiConfigApiSaveConfig({required AppConfig config});

  Future<String> crateApiAgentApiSaveConfigToDisk();

  Future<List<AgentEvent>> crateApiAgentApiSendMessage({
    required String sessionId,
    required String message,
  });

  Stream<AgentEvent> crateApiAgentApiSendMessageStream({
    required String sessionId,
    required String message,
  });

  Future<void> crateApiAgentApiSwitchSession({required String sessionId});

  Future<String> crateApiWorkspaceApiUpdateAgentConfig({
    int? maxToolIterations,
    int? maxHistoryMessages,
    bool? parallelTools,
    bool? compactContext,
  });

  Future<String> crateApiWorkspaceApiUpdateAutonomyLevel({
    required String level,
  });

  Future<String> crateApiAgentApiUpdateConfig({
    String? provider,
    String? model,
    String? apiKey,
    String? apiBase,
    double? temperature,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AppConfig> crateApiConfigApiAppConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigApiAppConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigApiAppConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "app_config_default", argNames: []);

  @override
  Future<void> crateApiAgentApiClearSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiClearSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiClearSessionConstMeta =>
      const TaskConstMeta(debugName: "clear_session", argNames: []);

  @override
  ChatSessionInfo crateApiAgentApiCreateSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_session_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiCreateSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiCreateSessionConstMeta =>
      const TaskConstMeta(debugName: "create_session", argNames: []);

  @override
  Future<AgentConfigDto> crateApiWorkspaceApiGetAgentConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiGetAgentConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiGetAgentConfigConstMeta =>
      const TaskConstMeta(debugName: "get_agent_config", argNames: []);

  @override
  Future<AutonomyConfig> crateApiWorkspaceApiGetAutonomyConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_autonomy_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiGetAutonomyConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiGetAutonomyConfigConstMeta =>
      const TaskConstMeta(debugName: "get_autonomy_config", argNames: []);

  @override
  Future<CostConfigDto> crateApiWorkspaceApiGetCostConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cost_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiGetCostConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiGetCostConfigConstMeta =>
      const TaskConstMeta(debugName: "get_cost_config", argNames: []);

  @override
  Future<AppConfig> crateApiAgentApiGetCurrentConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiGetCurrentConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiGetCurrentConfigConstMeta =>
      const TaskConstMeta(debugName: "get_current_config", argNames: []);

  @override
  Future<MemoryConfigDto> crateApiWorkspaceApiGetMemoryConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_memory_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiGetMemoryConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiGetMemoryConfigConstMeta =>
      const TaskConstMeta(debugName: "get_memory_config", argNames: []);

  @override
  Future<RuntimeStatus> crateApiAgentApiGetRuntimeStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_runtime_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiGetRuntimeStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiGetRuntimeStatusConstMeta =>
      const TaskConstMeta(debugName: "get_runtime_status", argNames: []);

  @override
  Future<WorkspaceConfig> crateApiWorkspaceApiGetWorkspaceConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiGetWorkspaceConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiGetWorkspaceConfigConstMeta =>
      const TaskConstMeta(debugName: "get_workspace_config", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiAgentApiInitRuntime() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiInitRuntimeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiInitRuntimeConstMeta =>
      const TaskConstMeta(debugName: "init_runtime", argNames: []);

  @override
  Future<List<ChannelSummary>> crateApiWorkspaceApiListChannels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_channel_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiListChannelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiListChannelsConstMeta =>
      const TaskConstMeta(debugName: "list_channels", argNames: []);

  @override
  List<ProviderInfo> crateApiConfigApiListProviders() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_provider_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigApiListProvidersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigApiListProvidersConstMeta =>
      const TaskConstMeta(debugName: "list_providers", argNames: []);

  @override
  List<ToolSpecDto> crateApiAgentApiListTools() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tool_spec_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiListToolsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiListToolsConstMeta =>
      const TaskConstMeta(debugName: "list_tools", argNames: []);

  @override
  Future<List<ToolInfo>> crateApiWorkspaceApiListToolsWithStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tool_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiListToolsWithStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiListToolsWithStatusConstMeta =>
      const TaskConstMeta(debugName: "list_tools_with_status", argNames: []);

  @override
  Future<AppConfig> crateApiConfigApiLoadConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigApiLoadConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigApiLoadConfigConstMeta =>
      const TaskConstMeta(debugName: "load_config", argNames: []);

  @override
  Future<bool> crateApiConfigApiSaveConfig({required AppConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_app_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigApiSaveConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigApiSaveConfigConstMeta =>
      const TaskConstMeta(debugName: "save_config", argNames: ["config"]);

  @override
  Future<String> crateApiAgentApiSaveConfigToDisk() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiSaveConfigToDiskConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiSaveConfigToDiskConstMeta =>
      const TaskConstMeta(debugName: "save_config_to_disk", argNames: []);

  @override
  Future<List<AgentEvent>> crateApiAgentApiSendMessage({
    required String sessionId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_agent_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiSendMessageConstMeta,
        argValues: [sessionId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_message",
        argNames: ["sessionId", "message"],
      );

  @override
  Stream<AgentEvent> crateApiAgentApiSendMessageStream({
    required String sessionId,
    required String message,
  }) {
    final sink = RustStreamSink<AgentEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_String(message, serializer);
            sse_encode_StreamSink_agent_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAgentApiSendMessageStreamConstMeta,
          argValues: [sessionId, message, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAgentApiSendMessageStreamConstMeta =>
      const TaskConstMeta(
        debugName: "send_message_stream",
        argNames: ["sessionId", "message", "sink"],
      );

  @override
  Future<void> crateApiAgentApiSwitchSession({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiSwitchSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiSwitchSessionConstMeta =>
      const TaskConstMeta(debugName: "switch_session", argNames: ["sessionId"]);

  @override
  Future<String> crateApiWorkspaceApiUpdateAgentConfig({
    int? maxToolIterations,
    int? maxHistoryMessages,
    bool? parallelTools,
    bool? compactContext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(maxToolIterations, serializer);
          sse_encode_opt_box_autoadd_u_32(maxHistoryMessages, serializer);
          sse_encode_opt_box_autoadd_bool(parallelTools, serializer);
          sse_encode_opt_box_autoadd_bool(compactContext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiUpdateAgentConfigConstMeta,
        argValues: [
          maxToolIterations,
          maxHistoryMessages,
          parallelTools,
          compactContext,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiUpdateAgentConfigConstMeta =>
      const TaskConstMeta(
        debugName: "update_agent_config",
        argNames: [
          "maxToolIterations",
          "maxHistoryMessages",
          "parallelTools",
          "compactContext",
        ],
      );

  @override
  Future<String> crateApiWorkspaceApiUpdateAutonomyLevel({
    required String level,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(level, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceApiUpdateAutonomyLevelConstMeta,
        argValues: [level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceApiUpdateAutonomyLevelConstMeta =>
      const TaskConstMeta(
        debugName: "update_autonomy_level",
        argNames: ["level"],
      );

  @override
  Future<String> crateApiAgentApiUpdateConfig({
    String? provider,
    String? model,
    String? apiKey,
    String? apiBase,
    double? temperature,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(provider, serializer);
          sse_encode_opt_String(model, serializer);
          sse_encode_opt_String(apiKey, serializer);
          sse_encode_opt_String(apiBase, serializer);
          sse_encode_opt_box_autoadd_f_64(temperature, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentApiUpdateConfigConstMeta,
        argValues: [provider, model, apiKey, apiBase, temperature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApiUpdateConfigConstMeta =>
      const TaskConstMeta(
        debugName: "update_config",
        argNames: ["provider", "model", "apiKey", "apiBase", "temperature"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AgentEvent> dco_decode_StreamSink_agent_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentConfigDto dco_decode_agent_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AgentConfigDto(
      maxToolIterations: dco_decode_u_32(arr[0]),
      maxHistoryMessages: dco_decode_u_32(arr[1]),
      parallelTools: dco_decode_bool(arr[2]),
      toolDispatcher: dco_decode_String(arr[3]),
      compactContext: dco_decode_bool(arr[4]),
    );
  }

  @protected
  AgentEvent dco_decode_agent_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AgentEvent_Thinking();
      case 1:
        return AgentEvent_TextDelta(text: dco_decode_String(raw[1]));
      case 2:
        return AgentEvent_ToolCallStart(
          name: dco_decode_String(raw[1]),
          args: dco_decode_String(raw[2]),
        );
      case 3:
        return AgentEvent_ToolCallEnd(
          name: dco_decode_String(raw[1]),
          result: dco_decode_String(raw[2]),
          success: dco_decode_bool(raw[3]),
        );
      case 4:
        return AgentEvent_MessageComplete(
          inputTokens: dco_decode_opt_box_autoadd_u_64(raw[1]),
          outputTokens: dco_decode_opt_box_autoadd_u_64(raw[2]),
        );
      case 5:
        return AgentEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AppConfig dco_decode_app_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AppConfig(
      provider: dco_decode_String(arr[0]),
      model: dco_decode_String(arr[1]),
      apiKey: dco_decode_String(arr[2]),
      apiBase: dco_decode_opt_String(arr[3]),
      temperature: dco_decode_f_64(arr[4]),
      maxToolIterations: dco_decode_u_32(arr[5]),
      language: dco_decode_String(arr[6]),
    );
  }

  @protected
  AutonomyConfig dco_decode_autonomy_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return AutonomyConfig(
      level: dco_decode_String(arr[0]),
      workspaceOnly: dco_decode_bool(arr[1]),
      allowedCommands: dco_decode_list_String(arr[2]),
      forbiddenPaths: dco_decode_list_String(arr[3]),
      maxActionsPerHour: dco_decode_u_32(arr[4]),
      maxCostPerDayCents: dco_decode_u_32(arr[5]),
      requireApprovalForMediumRisk: dco_decode_bool(arr[6]),
      blockHighRiskCommands: dco_decode_bool(arr[7]),
      autoApprove: dco_decode_list_String(arr[8]),
      alwaysAsk: dco_decode_list_String(arr[9]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppConfig dco_decode_box_autoadd_app_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_config(raw);
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChannelSummary dco_decode_channel_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChannelSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      channelType: dco_decode_String(arr[2]),
      enabled: dco_decode_bool(arr[3]),
      description: dco_decode_String(arr[4]),
    );
  }

  @protected
  ChatSessionInfo dco_decode_chat_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChatSessionInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
      updatedAt: dco_decode_i_64(arr[3]),
      messageCount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  CostConfigDto dco_decode_cost_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CostConfigDto(
      enabled: dco_decode_bool(arr[0]),
      dailyLimitUsd: dco_decode_f_64(arr[1]),
      monthlyLimitUsd: dco_decode_f_64(arr[2]),
      warnAtPercent: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AgentEvent> dco_decode_list_agent_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_agent_event).toList();
  }

  @protected
  List<ChannelSummary> dco_decode_list_channel_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_channel_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProviderInfo> dco_decode_list_provider_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_provider_info).toList();
  }

  @protected
  List<ToolInfo> dco_decode_list_tool_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tool_info).toList();
  }

  @protected
  List<ToolSpecDto> dco_decode_list_tool_spec_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tool_spec_dto).toList();
  }

  @protected
  MemoryConfigDto dco_decode_memory_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MemoryConfigDto(
      backend: dco_decode_String(arr[0]),
      autoSave: dco_decode_bool(arr[1]),
      hygieneEnabled: dco_decode_bool(arr[2]),
      archiveAfterDays: dco_decode_u_32(arr[3]),
      purgeAfterDays: dco_decode_u_32(arr[4]),
      conversationRetentionDays: dco_decode_u_32(arr[5]),
      embeddingProvider: dco_decode_String(arr[6]),
      embeddingModel: dco_decode_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  ProviderInfo dco_decode_provider_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProviderInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      providerType: dco_decode_provider_type(arr[2]),
      models: dco_decode_list_String(arr[3]),
      requiresApiKey: dco_decode_bool(arr[4]),
      requiresApiBase: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ProviderType dco_decode_provider_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProviderType.values[raw as int];
  }

  @protected
  RuntimeStatus dco_decode_runtime_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RuntimeStatus(
      initialized: dco_decode_bool(arr[0]),
      hasApiKey: dco_decode_bool(arr[1]),
      provider: dco_decode_String(arr[2]),
      model: dco_decode_String(arr[3]),
    );
  }

  @protected
  ToolInfo dco_decode_tool_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ToolInfo(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      autoApproved: dco_decode_bool(arr[3]),
      alwaysAsk: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ToolSpecDto dco_decode_tool_spec_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ToolSpecDto(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkspaceConfig dco_decode_workspace_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WorkspaceConfig(
      workspaceDir: dco_decode_String(arr[0]),
      configPath: dco_decode_String(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AgentEvent> sse_decode_StreamSink_agent_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentConfigDto sse_decode_agent_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_maxToolIterations = sse_decode_u_32(deserializer);
    var var_maxHistoryMessages = sse_decode_u_32(deserializer);
    var var_parallelTools = sse_decode_bool(deserializer);
    var var_toolDispatcher = sse_decode_String(deserializer);
    var var_compactContext = sse_decode_bool(deserializer);
    return AgentConfigDto(
      maxToolIterations: var_maxToolIterations,
      maxHistoryMessages: var_maxHistoryMessages,
      parallelTools: var_parallelTools,
      toolDispatcher: var_toolDispatcher,
      compactContext: var_compactContext,
    );
  }

  @protected
  AgentEvent sse_decode_agent_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AgentEvent_Thinking();
      case 1:
        var var_text = sse_decode_String(deserializer);
        return AgentEvent_TextDelta(text: var_text);
      case 2:
        var var_name = sse_decode_String(deserializer);
        var var_args = sse_decode_String(deserializer);
        return AgentEvent_ToolCallStart(name: var_name, args: var_args);
      case 3:
        var var_name = sse_decode_String(deserializer);
        var var_result = sse_decode_String(deserializer);
        var var_success = sse_decode_bool(deserializer);
        return AgentEvent_ToolCallEnd(
          name: var_name,
          result: var_result,
          success: var_success,
        );
      case 4:
        var var_inputTokens = sse_decode_opt_box_autoadd_u_64(deserializer);
        var var_outputTokens = sse_decode_opt_box_autoadd_u_64(deserializer);
        return AgentEvent_MessageComplete(
          inputTokens: var_inputTokens,
          outputTokens: var_outputTokens,
        );
      case 5:
        var var_message = sse_decode_String(deserializer);
        return AgentEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AppConfig sse_decode_app_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_apiKey = sse_decode_String(deserializer);
    var var_apiBase = sse_decode_opt_String(deserializer);
    var var_temperature = sse_decode_f_64(deserializer);
    var var_maxToolIterations = sse_decode_u_32(deserializer);
    var var_language = sse_decode_String(deserializer);
    return AppConfig(
      provider: var_provider,
      model: var_model,
      apiKey: var_apiKey,
      apiBase: var_apiBase,
      temperature: var_temperature,
      maxToolIterations: var_maxToolIterations,
      language: var_language,
    );
  }

  @protected
  AutonomyConfig sse_decode_autonomy_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_level = sse_decode_String(deserializer);
    var var_workspaceOnly = sse_decode_bool(deserializer);
    var var_allowedCommands = sse_decode_list_String(deserializer);
    var var_forbiddenPaths = sse_decode_list_String(deserializer);
    var var_maxActionsPerHour = sse_decode_u_32(deserializer);
    var var_maxCostPerDayCents = sse_decode_u_32(deserializer);
    var var_requireApprovalForMediumRisk = sse_decode_bool(deserializer);
    var var_blockHighRiskCommands = sse_decode_bool(deserializer);
    var var_autoApprove = sse_decode_list_String(deserializer);
    var var_alwaysAsk = sse_decode_list_String(deserializer);
    return AutonomyConfig(
      level: var_level,
      workspaceOnly: var_workspaceOnly,
      allowedCommands: var_allowedCommands,
      forbiddenPaths: var_forbiddenPaths,
      maxActionsPerHour: var_maxActionsPerHour,
      maxCostPerDayCents: var_maxCostPerDayCents,
      requireApprovalForMediumRisk: var_requireApprovalForMediumRisk,
      blockHighRiskCommands: var_blockHighRiskCommands,
      autoApprove: var_autoApprove,
      alwaysAsk: var_alwaysAsk,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppConfig sse_decode_box_autoadd_app_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_config(deserializer));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChannelSummary sse_decode_channel_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_channelType = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    var var_description = sse_decode_String(deserializer);
    return ChannelSummary(
      id: var_id,
      name: var_name,
      channelType: var_channelType,
      enabled: var_enabled,
      description: var_description,
    );
  }

  @protected
  ChatSessionInfo sse_decode_chat_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_messageCount = sse_decode_u_32(deserializer);
    return ChatSessionInfo(
      id: var_id,
      title: var_title,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      messageCount: var_messageCount,
    );
  }

  @protected
  CostConfigDto sse_decode_cost_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_dailyLimitUsd = sse_decode_f_64(deserializer);
    var var_monthlyLimitUsd = sse_decode_f_64(deserializer);
    var var_warnAtPercent = sse_decode_u_8(deserializer);
    return CostConfigDto(
      enabled: var_enabled,
      dailyLimitUsd: var_dailyLimitUsd,
      monthlyLimitUsd: var_monthlyLimitUsd,
      warnAtPercent: var_warnAtPercent,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AgentEvent> sse_decode_list_agent_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AgentEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_agent_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChannelSummary> sse_decode_list_channel_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChannelSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_channel_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProviderInfo> sse_decode_list_provider_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ToolInfo> sse_decode_list_tool_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ToolInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tool_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ToolSpecDto> sse_decode_list_tool_spec_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ToolSpecDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tool_spec_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MemoryConfigDto sse_decode_memory_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_backend = sse_decode_String(deserializer);
    var var_autoSave = sse_decode_bool(deserializer);
    var var_hygieneEnabled = sse_decode_bool(deserializer);
    var var_archiveAfterDays = sse_decode_u_32(deserializer);
    var var_purgeAfterDays = sse_decode_u_32(deserializer);
    var var_conversationRetentionDays = sse_decode_u_32(deserializer);
    var var_embeddingProvider = sse_decode_String(deserializer);
    var var_embeddingModel = sse_decode_String(deserializer);
    return MemoryConfigDto(
      backend: var_backend,
      autoSave: var_autoSave,
      hygieneEnabled: var_hygieneEnabled,
      archiveAfterDays: var_archiveAfterDays,
      purgeAfterDays: var_purgeAfterDays,
      conversationRetentionDays: var_conversationRetentionDays,
      embeddingProvider: var_embeddingProvider,
      embeddingModel: var_embeddingModel,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProviderInfo sse_decode_provider_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_providerType = sse_decode_provider_type(deserializer);
    var var_models = sse_decode_list_String(deserializer);
    var var_requiresApiKey = sse_decode_bool(deserializer);
    var var_requiresApiBase = sse_decode_bool(deserializer);
    return ProviderInfo(
      id: var_id,
      name: var_name,
      providerType: var_providerType,
      models: var_models,
      requiresApiKey: var_requiresApiKey,
      requiresApiBase: var_requiresApiBase,
    );
  }

  @protected
  ProviderType sse_decode_provider_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProviderType.values[inner];
  }

  @protected
  RuntimeStatus sse_decode_runtime_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_initialized = sse_decode_bool(deserializer);
    var var_hasApiKey = sse_decode_bool(deserializer);
    var var_provider = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    return RuntimeStatus(
      initialized: var_initialized,
      hasApiKey: var_hasApiKey,
      provider: var_provider,
      model: var_model,
    );
  }

  @protected
  ToolInfo sse_decode_tool_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_autoApproved = sse_decode_bool(deserializer);
    var var_alwaysAsk = sse_decode_bool(deserializer);
    return ToolInfo(
      name: var_name,
      description: var_description,
      category: var_category,
      autoApproved: var_autoApproved,
      alwaysAsk: var_alwaysAsk,
    );
  }

  @protected
  ToolSpecDto sse_decode_tool_spec_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return ToolSpecDto(name: var_name, description: var_description);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkspaceConfig sse_decode_workspace_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_workspaceDir = sse_decode_String(deserializer);
    var var_configPath = sse_decode_String(deserializer);
    return WorkspaceConfig(
      workspaceDir: var_workspaceDir,
      configPath: var_configPath,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_agent_event_Sse(
    RustStreamSink<AgentEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_config_dto(
    AgentConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.maxToolIterations, serializer);
    sse_encode_u_32(self.maxHistoryMessages, serializer);
    sse_encode_bool(self.parallelTools, serializer);
    sse_encode_String(self.toolDispatcher, serializer);
    sse_encode_bool(self.compactContext, serializer);
  }

  @protected
  void sse_encode_agent_event(AgentEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AgentEvent_Thinking():
        sse_encode_i_32(0, serializer);
      case AgentEvent_TextDelta(text: final text):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
      case AgentEvent_ToolCallStart(name: final name, args: final args):
        sse_encode_i_32(2, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(args, serializer);
      case AgentEvent_ToolCallEnd(
        name: final name,
        result: final result,
        success: final success,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(result, serializer);
        sse_encode_bool(success, serializer);
      case AgentEvent_MessageComplete(
        inputTokens: final inputTokens,
        outputTokens: final outputTokens,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_opt_box_autoadd_u_64(inputTokens, serializer);
        sse_encode_opt_box_autoadd_u_64(outputTokens, serializer);
      case AgentEvent_Error(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_app_config(AppConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.apiKey, serializer);
    sse_encode_opt_String(self.apiBase, serializer);
    sse_encode_f_64(self.temperature, serializer);
    sse_encode_u_32(self.maxToolIterations, serializer);
    sse_encode_String(self.language, serializer);
  }

  @protected
  void sse_encode_autonomy_config(
    AutonomyConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.level, serializer);
    sse_encode_bool(self.workspaceOnly, serializer);
    sse_encode_list_String(self.allowedCommands, serializer);
    sse_encode_list_String(self.forbiddenPaths, serializer);
    sse_encode_u_32(self.maxActionsPerHour, serializer);
    sse_encode_u_32(self.maxCostPerDayCents, serializer);
    sse_encode_bool(self.requireApprovalForMediumRisk, serializer);
    sse_encode_bool(self.blockHighRiskCommands, serializer);
    sse_encode_list_String(self.autoApprove, serializer);
    sse_encode_list_String(self.alwaysAsk, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_config(
    AppConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_channel_summary(
    ChannelSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.channelType, serializer);
    sse_encode_bool(self.enabled, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_chat_session_info(
    ChatSessionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_u_32(self.messageCount, serializer);
  }

  @protected
  void sse_encode_cost_config_dto(
    CostConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_64(self.dailyLimitUsd, serializer);
    sse_encode_f_64(self.monthlyLimitUsd, serializer);
    sse_encode_u_8(self.warnAtPercent, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_agent_event(
    List<AgentEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_agent_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_channel_summary(
    List<ChannelSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_channel_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_provider_info(
    List<ProviderInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tool_info(
    List<ToolInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tool_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tool_spec_dto(
    List<ToolSpecDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tool_spec_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_memory_config_dto(
    MemoryConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.backend, serializer);
    sse_encode_bool(self.autoSave, serializer);
    sse_encode_bool(self.hygieneEnabled, serializer);
    sse_encode_u_32(self.archiveAfterDays, serializer);
    sse_encode_u_32(self.purgeAfterDays, serializer);
    sse_encode_u_32(self.conversationRetentionDays, serializer);
    sse_encode_String(self.embeddingProvider, serializer);
    sse_encode_String(self.embeddingModel, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_provider_info(ProviderInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_provider_type(self.providerType, serializer);
    sse_encode_list_String(self.models, serializer);
    sse_encode_bool(self.requiresApiKey, serializer);
    sse_encode_bool(self.requiresApiBase, serializer);
  }

  @protected
  void sse_encode_provider_type(ProviderType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_runtime_status(RuntimeStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.initialized, serializer);
    sse_encode_bool(self.hasApiKey, serializer);
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.model, serializer);
  }

  @protected
  void sse_encode_tool_info(ToolInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_bool(self.autoApproved, serializer);
    sse_encode_bool(self.alwaysAsk, serializer);
  }

  @protected
  void sse_encode_tool_spec_dto(ToolSpecDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workspace_config(
    WorkspaceConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.workspaceDir, serializer);
    sse_encode_String(self.configPath, serializer);
  }
}
