// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// List all configured delegate agents
Future<List<DelegateAgentDto>> listDelegateAgents() =>
    RustLib.instance.api.crateApiAgentsApiListDelegateAgents();

/// Get a single delegate agent by name
Future<DelegateAgentDto?> getDelegateAgent({required String name}) =>
    RustLib.instance.api.crateApiAgentsApiGetDelegateAgent(name: name);

/// Create or update a delegate agent. Returns "ok" on success, error string otherwise.
Future<String> upsertDelegateAgent({required DelegateAgentDto agent}) =>
    RustLib.instance.api.crateApiAgentsApiUpsertDelegateAgent(agent: agent);

/// Remove a delegate agent by name. Returns "ok" on success, error string otherwise.
Future<String> removeDelegateAgent({required String name}) =>
    RustLib.instance.api.crateApiAgentsApiRemoveDelegateAgent(name: name);

/// Return the count of currently configured delegate agents (sync for quick display)
int delegateAgentCount() =>
    RustLib.instance.api.crateApiAgentsApiDelegateAgentCount();

/// A delegate sub-agent configuration exposed to Flutter UI
class DelegateAgentDto {
  final String name;
  final String provider;
  final String model;
  final String? systemPrompt;
  final String? apiKey;
  final double? temperature;
  final int maxDepth;
  final bool agentic;
  final List<String> allowedTools;
  final int maxIterations;

  const DelegateAgentDto({
    required this.name,
    required this.provider,
    required this.model,
    this.systemPrompt,
    this.apiKey,
    this.temperature,
    required this.maxDepth,
    required this.agentic,
    required this.allowedTools,
    required this.maxIterations,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      systemPrompt.hashCode ^
      apiKey.hashCode ^
      temperature.hashCode ^
      maxDepth.hashCode ^
      agentic.hashCode ^
      allowedTools.hashCode ^
      maxIterations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DelegateAgentDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          provider == other.provider &&
          model == other.model &&
          systemPrompt == other.systemPrompt &&
          apiKey == other.apiKey &&
          temperature == other.temperature &&
          maxDepth == other.maxDepth &&
          agentic == other.agentic &&
          allowedTools == other.allowedTools &&
          maxIterations == other.maxIterations;
}
