// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent_workspace_base_dir`, `get_binding_for_session`, `persist_store`, `resolve_workspace_config`, `session_bindings`, `store_file_path`, `workspace_store`, `write_identity_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AgentWorkspaceStore`, `PersistedAgentWorkspace`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Initialize agent workspace store — load from disk
Future<String> initAgentWorkspaceStore() =>
    RustLib.instance.api.crateApiAgentWorkspaceApiInitAgentWorkspaceStore();

/// List all agent workspaces (summary only)
Future<List<AgentWorkspaceSummary>> listAgentWorkspaces() =>
    RustLib.instance.api.crateApiAgentWorkspaceApiListAgentWorkspaces();

/// Get full details of a single agent workspace
Future<AgentWorkspaceDto?> getAgentWorkspace({required String workspaceId}) =>
    RustLib.instance.api.crateApiAgentWorkspaceApiGetAgentWorkspace(
      workspaceId: workspaceId,
    );

/// Create or update an agent workspace
Future<String> upsertAgentWorkspace({required AgentWorkspaceDto workspace}) =>
    RustLib.instance.api.crateApiAgentWorkspaceApiUpsertAgentWorkspace(
      workspace: workspace,
    );

/// Delete an agent workspace
Future<String> deleteAgentWorkspace({required String workspaceId}) => RustLib
    .instance
    .api
    .crateApiAgentWorkspaceApiDeleteAgentWorkspace(workspaceId: workspaceId);

/// Get the workspace directory path for an agent workspace
Future<String> getAgentWorkspaceDir({required String workspaceId}) => RustLib
    .instance
    .api
    .crateApiAgentWorkspaceApiGetAgentWorkspaceDir(workspaceId: workspaceId);

/// Bind a session to an agent workspace. The next time the session's agent
/// is created, it will use this workspace's identity files.
Future<String> bindSessionToAgent({
  required String sessionId,
  required String workspaceId,
}) => RustLib.instance.api.crateApiAgentWorkspaceApiBindSessionToAgent(
  sessionId: sessionId,
  workspaceId: workspaceId,
);

/// Unbind a session from any agent workspace (revert to default).
Future<String> unbindSessionAgent({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiAgentWorkspaceApiUnbindSessionAgent(sessionId: sessionId);

/// Get the agent workspace ID bound to a session, if any.
Future<String?> getSessionAgentBinding({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiAgentWorkspaceApiGetSessionAgentBinding(sessionId: sessionId);

/// An agent workspace configuration exposed to Flutter UI
class AgentWorkspaceDto {
  /// Unique identifier for this agent workspace
  final String id;

  /// Display name (e.g. "Product Manager", "Flutter Dev")
  final String name;

  /// Short description of this agent's role
  final String description;

  /// Optional emoji/icon identifier
  final String avatar;

  /// Workspace directory path
  final String workspaceDir;

  /// Whether this workspace is active/enabled
  final bool enabled;

  /// Custom system prompt override (if any)
  final String systemPrompt;

  /// Contents of SOUL.md
  final String soulMd;

  /// Contents of AGENTS.md
  final String agentsMd;

  /// Contents of USER.md
  final String userMd;

  /// Contents of IDENTITY.md
  final String identityMd;

  /// Optional color tag (hex string like "#FF5722")
  final String colorTag;

  /// Created timestamp (epoch seconds)
  final PlatformInt64 createdAt;

  /// Updated timestamp (epoch seconds)
  final PlatformInt64 updatedAt;

  const AgentWorkspaceDto({
    required this.id,
    required this.name,
    required this.description,
    required this.avatar,
    required this.workspaceDir,
    required this.enabled,
    required this.systemPrompt,
    required this.soulMd,
    required this.agentsMd,
    required this.userMd,
    required this.identityMd,
    required this.colorTag,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      avatar.hashCode ^
      workspaceDir.hashCode ^
      enabled.hashCode ^
      systemPrompt.hashCode ^
      soulMd.hashCode ^
      agentsMd.hashCode ^
      userMd.hashCode ^
      identityMd.hashCode ^
      colorTag.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentWorkspaceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          avatar == other.avatar &&
          workspaceDir == other.workspaceDir &&
          enabled == other.enabled &&
          systemPrompt == other.systemPrompt &&
          soulMd == other.soulMd &&
          agentsMd == other.agentsMd &&
          userMd == other.userMd &&
          identityMd == other.identityMd &&
          colorTag == other.colorTag &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Summary for listing agent workspaces in UI
class AgentWorkspaceSummary {
  final String id;
  final String name;
  final String description;
  final String avatar;
  final bool enabled;
  final String colorTag;

  const AgentWorkspaceSummary({
    required this.id,
    required this.name,
    required this.description,
    required this.avatar,
    required this.enabled,
    required this.colorTag,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      avatar.hashCode ^
      enabled.hashCode ^
      colorTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentWorkspaceSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          avatar == other.avatar &&
          enabled == other.enabled &&
          colorTag == other.colorTag;
}
