// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_notification`, `notification_sender`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Subscribe to cron job execution notifications.
/// Flutter calls this once on startup; the sink stays open for the app lifetime.
Stream<CronNotification> subscribeCronNotifications() => RustLib.instance.api
    .crateApiCronNotificationApiSubscribeCronNotifications();

/// Notification emitted after a cron job finishes execution.
/// Streamed to Flutter so the UI can display a toast and optionally
/// inject the result into a chat session.
class CronNotification {
  /// Cron job ID
  final String jobId;

  /// Human-readable job name (may be empty)
  final String jobName;

  /// "shell" or "agent"
  final String jobType;

  /// "isolated" or "main"
  final String sessionTarget;

  /// Actual session ID to inject into (when session_target == "main")
  final String targetSessionId;

  /// "ok" or "error"
  final String status;

  /// Execution output / agent response (truncated)
  final String output;

  /// The prompt that was sent (agent jobs only)
  final String prompt;

  /// Wall-clock duration in milliseconds
  final PlatformInt64 durationMs;

  /// UTC epoch seconds when the job finished
  final PlatformInt64 finishedAt;

  const CronNotification({
    required this.jobId,
    required this.jobName,
    required this.jobType,
    required this.sessionTarget,
    required this.targetSessionId,
    required this.status,
    required this.output,
    required this.prompt,
    required this.durationMs,
    required this.finishedAt,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      jobName.hashCode ^
      jobType.hashCode ^
      sessionTarget.hashCode ^
      targetSessionId.hashCode ^
      status.hashCode ^
      output.hashCode ^
      prompt.hashCode ^
      durationMs.hashCode ^
      finishedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronNotification &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          jobName == other.jobName &&
          jobType == other.jobType &&
          sessionTarget == other.sessionTarget &&
          targetSessionId == other.targetSessionId &&
          status == other.status &&
          output == other.output &&
          prompt == other.prompt &&
          durationMs == other.durationMs &&
          finishedAt == other.finishedAt;
}
