// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_server`, `hashmap_to_kvs`, `kvs_to_hashmap`, `server_to_dto`, `string_to_transport`, `transport_to_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Get MCP configuration
Future<McpConfigDto> getMcpConfig() =>
    RustLib.instance.api.crateApiMcpApiGetMcpConfig();

/// List all configured MCP servers
Future<List<McpServerDto>> listMcpServers() =>
    RustLib.instance.api.crateApiMcpApiListMcpServers();

/// Enable or disable MCP
Future<String> setMcpEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiMcpApiSetMcpEnabled(enabled: enabled);

/// Add an MCP server. Returns "ok" or "error: ...".
Future<String> addMcpServer({required McpServerDto server}) =>
    RustLib.instance.api.crateApiMcpApiAddMcpServer(server: server);

/// Update an existing MCP server by name. Returns "ok" or "error: ...".
Future<String> updateMcpServer({required McpServerDto server}) =>
    RustLib.instance.api.crateApiMcpApiUpdateMcpServer(server: server);

/// Remove an MCP server by name. Returns "ok" or "error: ...".
Future<String> removeMcpServer({required String name}) =>
    RustLib.instance.api.crateApiMcpApiRemoveMcpServer(name: name);

/// A key-value pair for HashMap serialization over FFI.
class KeyValueDto {
  final String key;
  final String value;

  const KeyValueDto({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyValueDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// MCP configuration overview
class McpConfigDto {
  final bool enabled;
  final List<McpServerDto> servers;

  const McpConfigDto({required this.enabled, required this.servers});

  @override
  int get hashCode => enabled.hashCode ^ servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpConfigDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          servers == other.servers;
}

/// MCP server DTO for Flutter bridge
class McpServerDto {
  final String name;

  /// "stdio" | "http" | "sse"
  final String transport;
  final String url;
  final String command;
  final List<String> args;
  final List<KeyValueDto> env;
  final List<KeyValueDto> headers;
  final BigInt? toolTimeoutSecs;

  const McpServerDto({
    required this.name,
    required this.transport,
    required this.url,
    required this.command,
    required this.args,
    required this.env,
    required this.headers,
    this.toolTimeoutSecs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      transport.hashCode ^
      url.hashCode ^
      command.hashCode ^
      args.hashCode ^
      env.hashCode ^
      headers.hashCode ^
      toolTimeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpServerDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          transport == other.transport &&
          url == other.url &&
          command == other.command &&
          args == other.args &&
          env == other.env &&
          headers == other.headers &&
          toolTimeoutSecs == other.toolTimeoutSecs;
}
