// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `count_skills_in_dir`, `load_skills_from_dir`, `parse_skill_md`, `parse_skill_toml`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Get skills configuration from zeroclaw config
Future<SkillsConfigDto> getSkillsConfig() =>
    RustLib.instance.api.crateApiSkillsApiGetSkillsConfig();

/// List all available skills (local + community if enabled)
Future<List<SkillDto>> listSkills() =>
    RustLib.instance.api.crateApiSkillsApiListSkills();

/// Toggle the open skills feature on/off
Future<String> toggleOpenSkills({required bool enabled}) =>
    RustLib.instance.api.crateApiSkillsApiToggleOpenSkills(enabled: enabled);

/// Update prompt injection mode ("full" or "compact")
Future<String> updatePromptInjectionMode({required String mode}) =>
    RustLib.instance.api.crateApiSkillsApiUpdatePromptInjectionMode(mode: mode);

/// A skill loaded from the skills directory
class SkillDto {
  final String name;
  final String description;
  final String version;
  final String author;
  final List<String> tags;
  final List<SkillToolDto> tools;
  final List<String> prompts;
  final String source;

  const SkillDto({
    required this.name,
    required this.description,
    required this.version,
    required this.author,
    required this.tags,
    required this.tools,
    required this.prompts,
    required this.source,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      version.hashCode ^
      author.hashCode ^
      tags.hashCode ^
      tools.hashCode ^
      prompts.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          version == other.version &&
          author == other.author &&
          tags == other.tags &&
          tools == other.tools &&
          prompts == other.prompts &&
          source == other.source;
}

/// A tool defined within a skill
class SkillToolDto {
  final String name;
  final String description;
  final String kind;

  const SkillToolDto({
    required this.name,
    required this.description,
    required this.kind,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillToolDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          kind == other.kind;
}

/// Skills configuration overview
class SkillsConfigDto {
  final bool openSkillsEnabled;
  final String promptInjectionMode;
  final String skillsDir;
  final int localSkillsCount;
  final int communitySkillsCount;

  const SkillsConfigDto({
    required this.openSkillsEnabled,
    required this.promptInjectionMode,
    required this.skillsDir,
    required this.localSkillsCount,
    required this.communitySkillsCount,
  });

  @override
  int get hashCode =>
      openSkillsEnabled.hashCode ^
      promptInjectionMode.hashCode ^
      skillsDir.hashCode ^
      localSkillsCount.hashCode ^
      communitySkillsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillsConfigDto &&
          runtimeType == other.runtimeType &&
          openSkillsEnabled == other.openSkillsEnabled &&
          promptInjectionMode == other.promptInjectionMode &&
          skillsDir == other.skillsDir &&
          localSkillsCount == other.localSkillsCount &&
          communitySkillsCount == other.communitySkillsCount;
}
